import type { Metadata } from "next";
import {
  DM_Sans,
  DM_Mono,
  DM_Serif_Display,
} from "next/font/google";
import "./globals.css";
import Navigation from "@/components/Navigation";
import {PortalLoader} from "@/components/PortalLoader";

const dmSans = DM_Sans({
  variable: "--font-dm-sans",
  subsets: ["latin"],
});

const dmMono = DM_Mono({
  variable: "--font-dm-mono",
  subsets: ["latin"],
  weight: ["400", "500"],
});

const dmSerifDisplay = DM_Serif_Display({
  variable: "--font-dm-serif-display",
  subsets: ["latin"],
  style: ["normal", "italic"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    return (
    <html lang="en">
      <body
        className={`${dmSans.variable} ${dmMono.variable} ${dmSerifDisplay.variable} antialiased h-screen w-screen`}
      >
      <PortalLoader />
      <Navigation />
        {children}
      </body>
    </html>
  );
}
